Finishing up integration of openpgp jcop4 card functions

diff --git a/securerd/custom-scripts/signature_openssl b/securerd/custom-scripts/signature_openssl
--- a/securerd/custom-scripts/signature_openssl
+++ b/securerd/custom-scripts/signature_openssl
@@ -26,6 +26,9 @@ if [ -n "$KERNEL2" ]; then
     echo -n "Checking signature vmlimuz"
     verify_signature "/boot/$KERNEL2" || fail "Kernel Failed signature check"
     echo "...Pass"
+    echo -n "Checking singature filesystem.squashfs"
+    verify_signature "/boot/live/filesystem.squashfs" || fail "filesystem.squashfs Failed signature check"
+    echo "...Pass"
 fi
 
 echo "Signatures passed"
diff --git a/securerd/custom-scripts/signature_pgp b/securerd/custom-scripts/signature_pgp
--- a/securerd/custom-scripts/signature_pgp
+++ b/securerd/custom-scripts/signature_pgp
@@ -29,6 +29,9 @@ if [ -n "$KERNEL2" ]; then
     echo -n "Checking signature vmlinuz"
     verify_signature "/boot/$KERNEL2" || fail "Kernel Failed signature check"
     echo "...Pass"
+    echo -n "Checking signature filesystem.squashfs "
+    verify_signature "/boot/live/filesystem.squashfs" || fail " filesystem.squashfs Failed signature check"
+    echo "...Pass"
 fi
 
 # Clean up temporary keyring
